import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { readFileSync } from "fs";
import { join } from "path";
import { Nav } from "@/components/nav/nav";
import { Footer } from "@/components/footer/footer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { JsonLd } from "@/components/seo/json-ld";
import { blogPosts, getBlogPost } from "@/lib/blog";
import {
  SITE_URL,
  graph,
  blogPostingNode,
  breadcrumbNode,
  faqPageNode,
} from "@/lib/seo";
import { parseFaq, wordCount } from "@/lib/faq-parser";

export function generateStaticParams() {
  return blogPosts.map((p) => ({ slug: p.slug }));
}

function readMdx(slug: string): string {
  try {
    return readFileSync(join(process.cwd(), "content/blog", `${slug}.mdx`), "utf-8");
  } catch {
    return "";
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getBlogPost(slug);
  if (!post) return {};
  const url = `${SITE_URL}/blog/${post.slug}`;
  return {
    title: post.title,
    description: post.excerpt,
    keywords: post.keywords,
    authors: [{ name: "Tomáš Hamerník", url: SITE_URL }],
    alternates: {
      canonical: `/blog/${post.slug}`,
      languages: {
        "cs-CZ": `/blog/${post.slug}`,
        "x-default": `/blog/${post.slug}`,
      },
    },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.excerpt,
      url,
      siteName: "Hamr Labs",
      locale: "cs_CZ",
      publishedTime: post.date,
      modifiedTime: post.date,
      authors: ["Tomáš Hamerník"],
      section: post.tag,
      tags: post.keywords,
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.excerpt,
    },
  };
}

function formatDate(iso: string) {
  const [y, m, d] = iso.split("-");
  return `${Number(d)}. ${Number(m)}. ${y}`;
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getBlogPost(slug);
  if (!post) notFound();

  const raw = readMdx(slug);
  const faqs = parseFaq(raw);
  const words = wordCount(raw);
  const { default: MDX } = await import(`@/content/blog/${slug}.mdx`);

  const breadcrumbs = [
    { name: "Domů", url: SITE_URL },
    { name: "Blog", url: `${SITE_URL}/blog` },
    { name: post.title, url: `${SITE_URL}/blog/${post.slug}` },
  ];

  const jsonLd = graph([
    blogPostingNode({
      title: post.title,
      description: post.excerpt,
      slug: post.slug,
      datePublished: post.date,
      section: post.tag,
      keywords: post.keywords,
      // Per-article branded OG image (generated by opengraph-image.tsx).
      // The query-less URL resolves to the same static file on Apache.
      imageUrl: `${SITE_URL}/blog/${post.slug}/opengraph-image`,
      wordCount: words,
    }),
    breadcrumbNode(breadcrumbs),
    ...(faqs.length ? [faqPageNode(faqs)] : []),
  ]);

  return (
    <>
      <JsonLd data={jsonLd} />
      <Nav />
      <main id="main" className="relative">
        {/* Header */}
        <header
          id="hero"
          className="relative pt-32 pb-12 md:pt-40 md:pb-16 border-b border-rule overflow-hidden"
        >
          <div className="absolute inset-0 aurora-bg opacity-60 pointer-events-none" />
          <div className="container-ultra relative max-w-3xl flex flex-col gap-6">
            {/* Visible breadcrumbs — mirror the BreadcrumbList schema */}
            <nav
              aria-label="Drobečková navigace"
              className="font-mono text-xs uppercase tracking-[0.12em] text-fg-muted flex items-center gap-2 flex-wrap"
            >
              <a href="/" className="hover:text-accent transition-colors">
                Domů
              </a>
              <span aria-hidden className="text-fg-subtle">
                /
              </span>
              <a href="/blog" className="hover:text-accent transition-colors">
                Blog
              </a>
              <span aria-hidden className="text-fg-subtle">
                /
              </span>
              <span className="text-fg-subtle normal-case tracking-normal truncate max-w-[60vw]">
                {post.title}
              </span>
            </nav>

            <div className="flex items-center gap-3 flex-wrap">
              <Badge>{post.tag}</Badge>
              <span className="font-mono text-[10px] uppercase tracking-[0.15em] text-fg-subtle">
                {formatDate(post.date)} · {post.readingMinutes} min čtení
              </span>
            </div>
            <h1 className="font-display leading-[1.1] tracking-[-0.02em] text-[clamp(32px,5vw,64px)] text-fg">
              {post.title}
            </h1>
          </div>
        </header>

        {/* Body */}
        <article className="container-ultra py-16 md:py-24 max-w-3xl">
          <MDX />
        </article>

        {/* CTA */}
        <section className="border-t border-rule py-20 md:py-28">
          <div className="container-ultra flex flex-col gap-6 items-start max-w-3xl">
            <h2 className="font-display leading-[1.15] tracking-[-0.02em] text-[clamp(28px,3.5vw,48px)] text-fg">
              Chcete to samé pro svůj byznys?
            </h2>
            <p className="font-sans text-lg text-fg-muted leading-relaxed max-w-lg">
              Pošlete stručný brief: firma, rozpočet, co řešíte. Vrátím se s
              návrhem, jak na to bych šel já.
            </p>
            <div className="flex flex-wrap gap-4">
              <a href="/#kontakt">
                <Button variant="primary">Chci konzultaci</Button>
              </a>
              <a href="/blog">
                <Button variant="secondary">← Zpět na blog</Button>
              </a>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
